plot_dir: "/work/y02/y02/awilkins/data/plots/archer2_jobdata_plots"
assocs_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacct_archer2_assocs_230129.csv"
node_events_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacctmgr_events_221019-230129.csv"
reservations_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/hpelongjobs_resv_tests/sinfo_reservations_070223_medhpelongjobs.csv"
job_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacct_2022-10-19_2023-01-29_allocations_noconvert.txt"

bf_max_job_test: 1000
bf_window: 5760
bf_continue: True
defer: True
default_queue_depth: 256
