assocs_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/sacctmgr_assocs_230222.csv"
qos_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/sacctmgr_qos_230223.csv"
node_events_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/sacctmgr_events_221019-230219.csv"
resv_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/sinfo_reservations_070223_highhpelongjobs.csv"
# resv_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/hpelongjobs_resv_tests/sinfo_reservations_070223_high224hpelongjobs.csv"
job_dump: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/sacct_2022-10-19_2022-11-09_allocations_noconvert.txt"
slurm_conf: "/unix/dune/awilkinson/hpe/data/data_paper/slurm_data/slurm_230221.conf"
considered_partitions: ["standard", "highmem"]

approx_excess_assocs: 1200

hpe_restrictlong_sliding_reservations: "/unix/dune/awilkinson/hpe/data/data_paper/HPE_Res_nids.txt"

bf_max_job_test: 1000
bf_window: 5760
bf_continue: True
defer: True
default_queue_depth: 256

sched_min_interval : 12000000
approx_bf_try_per_sec : 30
