plot_dir: "/work/y02/y02/awilkins/archer2_jobdata/data/plots/archer2_jobdata_plots"
assocs_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacct_archer2_assocs_230129.csv"
node_events_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacctmgr_events_221019-230129.csv"
reservations_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sinfo_reservations_070223_someHPErestrictlongremoved.csv"
job_dump: "/work/y02/y02/awilkins/data/slurm_data_dumps/sacct_2022-10-19_2022-11-09_allocations_noconvert.txt"

# "hpe_restrictlongjobs_sliding_reservations" : "/work/y02/y02/awilkins/archer2_jobdata/hpe_restrictlongjobs_schedule/sacct_2022-10-19_2022-11-09_allocations_noconvert_nids_hperestrictlongjobs_slidingres.pkl"

# Trying to ~ replicate actual performance (based on sdiag):
# - Don't really see backfill exceeding ~320 jobs with planned start times (sdiag shows it is
# max allowed cycle time when it has this number of start times planned)
# - Usually around 5 scheduling cycles per minute, this varies a lot with how busy slurm is though
bf_max_job_test: 320
bf_window: 5760
bf_continue: True
defer: True
default_queue_depth: 256
sched_min_interval: 12000000
